-- We-Rise production schema for Supabase Postgres
-- Run this entire file once in Supabase -> SQL Editor -> New query.

create extension if not exists pgcrypto;

create table if not exists public.campaigns (
  id uuid primary key default gen_random_uuid(),
  title varchar(250) not null,
  description text,
  goal numeric(12,2) not null check (goal > 0),
  raised numeric(12,2) not null default 0 check (raised >= 0),
  backers integer not null default 0 check (backers >= 0),
  creator varchar(80) not null default 'Anonymous We-Rise Lady',
  created_at timestamptz not null default now()
);

create table if not exists public.donations (
  id bigint generated by default as identity primary key,
  campaign_id uuid not null references public.campaigns(id) on delete cascade,
  donor varchar(80) not null default 'Anonymous',
  amount numeric(12,2) not null check (amount > 0),
  date date not null default current_date,
  time time not null default current_time,
  created_at timestamptz not null default now()
);

create index if not exists donations_campaign_idx on public.donations(campaign_id, created_at desc);

create table if not exists public.community_topics (
  id bigint generated by default as identity primary key,
  title varchar(250) not null,
  author varchar(80) not null default 'Anonymous We-Rise Lady',
  created_at timestamptz not null default now()
);

create table if not exists public.community_comments (
  id bigint generated by default as identity primary key,
  topic_id bigint not null references public.community_topics(id) on delete cascade,
  author varchar(80) not null default 'Anonymous We-Rise Lady',
  content varchar(250) not null,
  created_at timestamptz not null default now()
);

create index if not exists community_comments_topic_idx on public.community_comments(topic_id, created_at, id);

create table if not exists public.community_supports (
  topic_id bigint not null references public.community_topics(id) on delete cascade,
  supporter_key varchar(120) not null,
  created_at timestamptz not null default now(),
  primary key (topic_id, supporter_key)
);

create index if not exists community_supports_topic_idx on public.community_supports(topic_id);

create table if not exists public.referrals (
  id bigint generated by default as identity primary key,
  referrer varchar(120) not null,
  referred_email varchar(320),
  commission numeric(12,2) not null default 0,
  status varchar(30) not null default 'pending',
  created_at timestamptz not null default now()
);

create table if not exists public.member_profiles (
  member_key varchar(120) primary key,
  display_name varchar(80) not null,
  plan varchar(20) not null default 'free' check (plan in ('free', 'premium')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now()
);

create table if not exists public.private_conversations (
  id bigint generated by default as identity primary key,
  member_a_key varchar(120) not null references public.member_profiles(member_key) on delete cascade,
  member_b_key varchar(120) not null references public.member_profiles(member_key) on delete cascade,
  created_at timestamptz not null default now(),
  last_message_at timestamptz,
  constraint private_conversation_member_order check (member_a_key < member_b_key),
  constraint private_conversation_pair_unique unique (member_a_key, member_b_key)
);

create index if not exists private_conversations_a_idx on public.private_conversations(member_a_key, last_message_at desc);
create index if not exists private_conversations_b_idx on public.private_conversations(member_b_key, last_message_at desc);

create table if not exists public.private_messages (
  id bigint generated by default as identity primary key,
  conversation_id bigint not null references public.private_conversations(id) on delete cascade,
  sender_key varchar(120) not null references public.member_profiles(member_key) on delete cascade,
  receiver_key varchar(120) not null references public.member_profiles(member_key) on delete cascade,
  content varchar(2000) not null,
  created_at timestamptz not null default now(),
  read_at timestamptz
);

create index if not exists private_messages_conversation_idx on public.private_messages(conversation_id, id desc);
create index if not exists private_messages_unread_idx on public.private_messages(receiver_key, read_at, conversation_id);

-- Atomic donation write + campaign totals update.
create or replace function public.record_donation(
  p_campaign_id uuid,
  p_donor text,
  p_amount numeric
)
returns boolean
language plpgsql
as $$
begin
  if p_amount is null or p_amount <= 0 then
    raise exception 'Donation amount must be positive';
  end if;

  if not exists (select 1 from public.campaigns where id = p_campaign_id) then
    return false;
  end if;

  insert into public.donations (campaign_id, donor, amount)
  values (p_campaign_id, coalesce(nullif(trim(p_donor), ''), 'Anonymous'), p_amount);

  update public.campaigns
  set raised = raised + p_amount,
      backers = backers + 1
  where id = p_campaign_id;

  return true;
end;
$$;

-- Community feed with server-side reply/support counts and current-user support state.
create or replace function public.get_community_topics(p_supporter_key text default '')
returns table (
  id bigint,
  title text,
  author text,
  created_at timestamptz,
  replies bigint,
  supports bigint,
  supported boolean
)
language sql
stable
as $$
  select
    t.id,
    t.title::text,
    t.author::text,
    t.created_at,
    (select count(*) from public.community_comments c where c.topic_id = t.id) as replies,
    (select count(*) from public.community_supports s where s.topic_id = t.id) as supports,
    case
      when coalesce(p_supporter_key, '') = '' then false
      else exists (
        select 1 from public.community_supports mine
        where mine.topic_id = t.id and mine.supporter_key = p_supporter_key
      )
    end as supported
  from public.community_topics t
  order by t.created_at desc, t.id desc;
$$;

-- Toggle a support reaction and return the new state/count.
create or replace function public.toggle_community_support(p_topic_id bigint, p_supporter_key text)
returns table (supported boolean, supports bigint)
language plpgsql
as $$
declare
  topic_exists boolean;
begin
  select exists(select 1 from public.community_topics where id = p_topic_id) into topic_exists;
  if not topic_exists then
    return;
  end if;

  if exists (
    select 1 from public.community_supports
    where topic_id = p_topic_id and supporter_key = p_supporter_key
  ) then
    delete from public.community_supports
    where topic_id = p_topic_id and supporter_key = p_supporter_key;
    supported := false;
  else
    insert into public.community_supports(topic_id, supporter_key)
    values (p_topic_id, left(p_supporter_key, 120));
    supported := true;
  end if;

  select count(*) into supports
  from public.community_supports where topic_id = p_topic_id;
  return next;
end;
$$;

-- Inbox query kept in Postgres so Render only receives the small result set it needs.
create or replace function public.get_member_inbox(p_member_key text)
returns table (
  id bigint,
  created_at timestamptz,
  last_message_at timestamptz,
  other_member_key text,
  other_name text,
  last_message text,
  last_sender_key text,
  unread_count bigint
)
language sql
stable
as $$
  select
    conv.id,
    conv.created_at,
    conv.last_message_at,
    case when conv.member_a_key = p_member_key then conv.member_b_key else conv.member_a_key end::text as other_member_key,
    case when conv.member_a_key = p_member_key then profile_b.display_name else profile_a.display_name end::text as other_name,
    (
      select pm.content::text from public.private_messages pm
      where pm.conversation_id = conv.id
      order by pm.id desc limit 1
    ) as last_message,
    (
      select pm.sender_key::text from public.private_messages pm
      where pm.conversation_id = conv.id
      order by pm.id desc limit 1
    ) as last_sender_key,
    (
      select count(*) from public.private_messages unread
      where unread.conversation_id = conv.id
        and unread.receiver_key = p_member_key
        and unread.read_at is null
    ) as unread_count
  from public.private_conversations conv
  join public.member_profiles profile_a on profile_a.member_key = conv.member_a_key
  join public.member_profiles profile_b on profile_b.member_key = conv.member_b_key
  where conv.member_a_key = p_member_key or conv.member_b_key = p_member_key
  order by coalesce(conv.last_message_at, conv.created_at) desc, conv.id desc
  limit 100;
$$;

-- All tables are API-private. The browser never receives the service-role key.
alter table public.campaigns enable row level security;
alter table public.donations enable row level security;
alter table public.community_topics enable row level security;
alter table public.community_comments enable row level security;
alter table public.community_supports enable row level security;
alter table public.referrals enable row level security;
alter table public.member_profiles enable row level security;
alter table public.private_conversations enable row level security;
alter table public.private_messages enable row level security;

-- Intentionally no anon/authenticated table policies yet.
-- The Render API uses SUPABASE_SERVICE_ROLE_KEY server-side and is the only data gateway in this phase.
