-- We-Rise: What-Now feature integration
-- Run this against the existing production Supabase project.

-- BackMi richer request fields
alter table public.campaigns add column if not exists reason varchar(160);
alter table public.campaigns add column if not exists category varchar(80) not null default 'Community support';
alter table public.campaigns add column if not exists explanation text;
alter table public.campaigns add column if not exists age integer;
alter table public.campaigns add column if not exists country varchar(80);
alter table public.campaigns add column if not exists deadline date;
alter table public.campaigns add column if not exists status varchar(30) not null default 'active';

-- Waitlist
create table if not exists public.waitlist_entries (
  id bigint generated by default as identity primary key,
  name varchar(80) not null,
  email varchar(320) not null,
  age integer not null check (age between 18 and 120),
  country varchar(80) not null,
  reason varchar(160) not null,
  explanation varchar(1200) not null,
  status varchar(30) not null default 'waiting',
  created_at timestamptz not null default now(),
  constraint waitlist_email_unique unique (email)
);
create index if not exists waitlist_created_idx on public.waitlist_entries(created_at desc);

-- Five trusted emergency contacts per member.
create table if not exists public.emergency_contacts (
  id bigint generated by default as identity primary key,
  member_key varchar(120) not null references public.member_profiles(member_key) on delete cascade,
  name varchar(80) not null,
  phone varchar(32) not null,
  relation varchar(80),
  position smallint not null check (position between 1 and 5),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint emergency_contact_position_unique unique (member_key, position)
);
create index if not exists emergency_contacts_member_idx on public.emergency_contacts(member_key, position);

create or replace function public.enforce_five_emergency_contacts()
returns trigger
language plpgsql
as $$
begin
  if (select count(*) from public.emergency_contacts where member_key = new.member_key) >= 5 then
    raise exception 'A member can have a maximum of 5 emergency contacts';
  end if;
  return new;
end;
$$;

drop trigger if exists enforce_five_emergency_contacts_trigger on public.emergency_contacts;
create trigger enforce_five_emergency_contacts_trigger
before insert on public.emergency_contacts
for each row execute function public.enforce_five_emergency_contacts();

-- Every panic event is logged. This does NOT claim emergency services were dispatched.
create table if not exists public.emergency_alerts (
  id bigint generated by default as identity primary key,
  member_key varchar(120) not null references public.member_profiles(member_key) on delete cascade,
  member_name varchar(80) not null,
  location_text varchar(300),
  latitude numeric(9,6),
  longitude numeric(9,6),
  message_text varchar(1500) not null,
  sms_configured boolean not null default false,
  sent_count integer not null default 0 check (sent_count between 0 and 5),
  status varchar(30) not null default 'manual_required',
  created_at timestamptz not null default now(),
  constraint emergency_latitude_check check (latitude is null or (latitude between -90 and 90)),
  constraint emergency_longitude_check check (longitude is null or (longitude between -180 and 180))
);
create index if not exists emergency_alerts_member_idx on public.emergency_alerts(member_key, created_at desc);

create table if not exists public.emergency_alert_recipients (
  id bigint generated by default as identity primary key,
  alert_id bigint not null references public.emergency_alerts(id) on delete cascade,
  contact_id bigint references public.emergency_contacts(id) on delete set null,
  contact_name varchar(80) not null,
  phone varchar(32) not null,
  status varchar(30) not null,
  provider_message_id varchar(120),
  error_message text,
  created_at timestamptz not null default now()
);
create index if not exists emergency_alert_recipients_alert_idx on public.emergency_alert_recipients(alert_id, created_at);

alter table public.waitlist_entries enable row level security;
alter table public.emergency_contacts enable row level security;
alter table public.emergency_alerts enable row level security;
alter table public.emergency_alert_recipients enable row level security;

-- Intentionally no browser policies in this phase.
-- The Render API remains the only gateway and uses the Supabase server secret.
