-- We-Rise Admin Control Centre V1
-- Run after 0012_registration_selfie_waitlist_goals.sql.
-- Adds admin audit history and a server-side dashboard metrics function.

create table if not exists public.admin_audit_log (
  id bigint generated by default as identity primary key,
  actor_member_key varchar(120) references public.member_profiles(member_key) on delete set null,
  actor_email varchar(320),
  actor_role varchar(30) not null,
  action varchar(80) not null,
  target_type varchar(60),
  target_key varchar(180),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists admin_audit_created_idx
  on public.admin_audit_log(created_at desc);
create index if not exists admin_audit_actor_idx
  on public.admin_audit_log(actor_member_key, created_at desc);
create index if not exists admin_audit_target_idx
  on public.admin_audit_log(target_type, target_key, created_at desc);

alter table public.admin_audit_log enable row level security;
-- No browser policies. Render remains the only gateway via the service-role key.

create or replace function public.get_we_rise_admin_metrics()
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_local_now timestamp := timezone('Africa/Johannesburg', now());
  v_today_start timestamptz;
  v_month_start timestamptz;
  v_result jsonb;
begin
  v_today_start := date_trunc('day', v_local_now) at time zone 'Africa/Johannesburg';
  v_month_start := date_trunc('month', v_local_now) at time zone 'Africa/Johannesburg';

  select jsonb_build_object(
    'total_members', (select count(*) from public.member_profiles),
    'new_today', (select count(*) from public.member_profiles where created_at >= v_today_start),
    'active_members', (select count(*) from public.member_profiles where membership_status = 'active'),
    'trial_members', (select count(*) from public.member_profiles where membership_status = 'trialing' and coalesce(trial_ends_at, now()) > now()),
    'past_due_members', (select count(*) from public.member_profiles where membership_status = 'past_due'),
    'cancelled_members', (select count(*) from public.member_profiles where membership_status = 'cancelled'),
    'waitlist_count', (select count(*) from public.waitlist_entries),
    'payments_today', (
      select count(*) from public.payment_transactions
      where status = 'complete' and coalesce(verified_at, created_at) >= v_today_start
    ),
    'revenue_today_zar', coalesce((
      select sum(coalesce(amount_gross_zar, expected_amount_zar)) from public.payment_transactions
      where status = 'complete' and coalesce(verified_at, created_at) >= v_today_start
    ), 0),
    'revenue_month_zar', coalesce((
      select sum(coalesce(amount_gross_zar, expected_amount_zar)) from public.payment_transactions
      where status = 'complete' and coalesce(verified_at, created_at) >= v_month_start
    ), 0),
    'joining_revenue_month_zar', coalesce((
      select sum(coalesce(amount_gross_zar, expected_amount_zar)) from public.payment_transactions
      where status = 'complete' and purpose = 'membership_joining' and coalesce(verified_at, created_at) >= v_month_start
    ), 0),
    'recurring_revenue_month_zar', coalesce((
      select sum(coalesce(amount_gross_zar, expected_amount_zar)) from public.payment_transactions
      where status = 'complete' and purpose = 'membership_recurring' and coalesce(verified_at, created_at) >= v_month_start
    ), 0),
    'failed_payments_month', (
      select count(*) from public.payment_transactions
      where status = 'failed' and created_at >= v_month_start
    ),
    'estimated_mrr_zar', coalesce((
      select sum(coalesce(subscription_monthly_amount_zar, 0))
      from public.member_profiles
      where membership_status = 'active'
        and payfast_subscription_token is not null
        and subscription_cancelled_at is null
    ), 0)
  ) into v_result;

  return v_result;
end;
$$;

-- Dashboard aggregate is backend-only. Do not expose this SECURITY DEFINER RPC
-- through the browser's anon/authenticated Supabase roles.
revoke all on function public.get_we_rise_admin_metrics() from public;
revoke all on function public.get_we_rise_admin_metrics() from anon;
revoke all on function public.get_we_rise_admin_metrics() from authenticated;
grant execute on function public.get_we_rise_admin_metrics() to service_role;
