-- We-Rise Admin Push Notifications
-- Run after 0013_admin_control_center.sql.
-- Persistent admin alerts + per-admin read state + browser/PWA push subscriptions.

create table if not exists public.admin_notifications (
  id bigint generated by default as identity primary key,
  type varchar(60) not null,
  member_key varchar(120) references public.member_profiles(member_key) on delete set null,
  title varchar(160) not null,
  body varchar(500) not null,
  url varchar(500) not null default '/admin',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists admin_notifications_created_idx
  on public.admin_notifications(created_at desc);
create index if not exists admin_notifications_member_idx
  on public.admin_notifications(member_key, created_at desc);

create table if not exists public.admin_notification_reads (
  notification_id bigint not null references public.admin_notifications(id) on delete cascade,
  admin_member_key varchar(120) not null references public.member_profiles(member_key) on delete cascade,
  read_at timestamptz not null default now(),
  primary key (notification_id, admin_member_key)
);

create index if not exists admin_notification_reads_admin_idx
  on public.admin_notification_reads(admin_member_key, read_at desc);

create table if not exists public.admin_push_subscriptions (
  id bigint generated by default as identity primary key,
  admin_member_key varchar(120) not null references public.member_profiles(member_key) on delete cascade,
  endpoint text not null unique,
  p256dh text not null,
  auth text not null,
  user_agent varchar(500),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists admin_push_subscriptions_admin_idx
  on public.admin_push_subscriptions(admin_member_key, updated_at desc);

alter table public.admin_notifications enable row level security;
alter table public.admin_notification_reads enable row level security;
alter table public.admin_push_subscriptions enable row level security;

-- No browser policies are added. The Render API is the only gateway and uses
-- the Supabase service-role key after enforcing OWNER/ADMIN authorization.

create or replace function public.mark_all_admin_notifications_read(p_admin_member_key varchar)
returns void
language sql
security definer
set search_path = public
as $$
  insert into public.admin_notification_reads (notification_id, admin_member_key, read_at)
  select n.id, p_admin_member_key, now()
  from public.admin_notifications n
  on conflict (notification_id, admin_member_key)
  do update set read_at = excluded.read_at;
$$;

revoke all on function public.mark_all_admin_notifications_read(varchar) from public;
revoke all on function public.mark_all_admin_notifications_read(varchar) from anon;
revoke all on function public.mark_all_admin_notifications_read(varchar) from authenticated;
grant execute on function public.mark_all_admin_notifications_read(varchar) to service_role;
