-- We-Rise Referral & Earnings Engine
-- Shared attribution for Resellers and RentIt / HuurDit.
-- Run after 0015_admin_remove_user_trial_notifications.sql.

-- A referral is permanently attached to the member who first registered through
-- a valid We-Rise referral code. It cannot be replaced later.
alter table public.member_profiles
  add column if not exists referred_by_member_key varchar(120),
  add column if not exists referral_code_used varchar(32),
  add column if not exists referral_program_used varchar(20),
  add column if not exists referred_at timestamptz;

do $$
begin
  alter table public.member_profiles
    add constraint member_profiles_referred_by_fk
    foreign key (referred_by_member_key) references public.member_profiles(member_key) on delete set null;
exception when duplicate_object then null;
end $$;

do $$
begin
  alter table public.member_profiles
    add constraint member_profiles_referral_program_check
    check (referral_program_used is null or referral_program_used in ('reseller', 'huurdit'));
exception when duplicate_object then null;
end $$;

do $$
begin
  alter table public.member_profiles
    add constraint member_profiles_no_self_referral_check
    check (referred_by_member_key is null or referred_by_member_key <> member_key);
exception when duplicate_object then null;
end $$;

create index if not exists member_profiles_referred_by_idx
  on public.member_profiles(referred_by_member_key, created_at desc);

create or replace function public.prevent_referral_attribution_change()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if old.referred_by_member_key is not null and (
    new.referred_by_member_key is distinct from old.referred_by_member_key
    or new.referral_code_used is distinct from old.referral_code_used
    or new.referral_program_used is distinct from old.referral_program_used
    or new.referred_at is distinct from old.referred_at
  ) then
    raise exception 'Referral attribution is permanent once assigned';
  end if;
  return new;
end;
$$;

drop trigger if exists protect_referral_attribution_trigger on public.member_profiles;
create trigger protect_referral_attribution_trigger
before update of referred_by_member_key, referral_code_used, referral_program_used, referred_at
on public.member_profiles
for each row execute function public.prevent_referral_attribution_change();

-- One person may participate in both programs, each with its own permanent code.
create table if not exists public.referral_programs (
  id uuid primary key default gen_random_uuid(),
  member_key varchar(120) not null references public.member_profiles(member_key) on delete cascade,
  program_type varchar(20) not null check (program_type in ('reseller', 'huurdit')),
  referral_code varchar(32) not null unique,
  status varchar(20) not null default 'active' check (status in ('pending', 'active', 'inactive', 'suspended')),
  activation_payment_id uuid references public.payment_transactions(id) on delete set null,
  activated_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (member_key, program_type)
);

create index if not exists referral_programs_member_idx
  on public.referral_programs(member_key, program_type);
create index if not exists referral_programs_code_idx
  on public.referral_programs(referral_code);

-- Pricing/rules are server-side data rather than hard-coded into the browser.
create table if not exists public.referral_program_settings (
  program_type varchar(20) primary key check (program_type in ('reseller', 'huurdit')),
  activation_fee_zar numeric(12,2) not null default 0 check (activation_fee_zar >= 0),
  referral_earning_zar numeric(12,2) not null default 0 check (referral_earning_zar >= 0),
  qualifying_payment_purpose varchar(40) not null,
  updated_at timestamptz not null default now()
);

insert into public.referral_program_settings (program_type, activation_fee_zar, referral_earning_zar, qualifying_payment_purpose)
values
  ('reseller', 0, 0, 'membership_joining'),
  ('huurdit', 1800, 1000, 'huurdit_activation')
on conflict (program_type) do update
set activation_fee_zar = excluded.activation_fee_zar,
    referral_earning_zar = excluded.referral_earning_zar,
    qualifying_payment_purpose = excluded.qualifying_payment_purpose,
    updated_at = now();

-- Anonymous click events contain no IP address or browser fingerprint. They are
-- used only for simple referral-link performance counts in the admin dashboard.
create table if not exists public.referral_link_clicks (
  id bigint generated by default as identity primary key,
  referral_program_id uuid not null references public.referral_programs(id) on delete cascade,
  referral_code varchar(32) not null,
  created_at timestamptz not null default now()
);

create index if not exists referral_link_clicks_program_idx
  on public.referral_link_clicks(referral_program_id, created_at desc);

-- A conversion becomes Owed only after a verified Paystack payment that matches
-- that program's qualifying purpose. Reseller referrals are tracked without
-- inventing a commission amount because the existing Reseller model uses the
-- reseller's own added profit rather than a hard-coded We-Rise commission.
create table if not exists public.referral_conversions (
  id uuid primary key default gen_random_uuid(),
  referrer_member_key varchar(120) not null references public.member_profiles(member_key) on delete restrict,
  referred_member_key varchar(120) not null references public.member_profiles(member_key) on delete restrict,
  referral_program_id uuid not null references public.referral_programs(id) on delete restrict,
  program_type varchar(20) not null check (program_type in ('reseller', 'huurdit')),
  conversion_type varchar(40) not null,
  qualifying_payment_id uuid references public.payment_transactions(id) on delete restrict,
  earning_amount_zar numeric(12,2) not null default 0 check (earning_amount_zar >= 0),
  status varchar(20) not null default 'tracked' check (status in ('tracked', 'owed', 'paid', 'void')),
  qualified_at timestamptz,
  paid_at timestamptz,
  payout_reference varchar(160),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (referred_member_key, conversion_type)
);

create index if not exists referral_conversions_referrer_idx
  on public.referral_conversions(referrer_member_key, created_at desc);
create index if not exists referral_conversions_status_idx
  on public.referral_conversions(status, program_type, created_at desc);

-- Paystack can now record the once-off R1800 RentIt/HuurDit activation.
alter table public.payment_transactions
  drop constraint if exists payment_transactions_purpose_check;
alter table public.payment_transactions
  add constraint payment_transactions_purpose_check
  check (purpose in ('membership_joining', 'membership_recurring', 'backmi_gift', 'huurdit_activation'));

-- Capture first-valid referral attribution at auth-account creation time.
create or replace function public.handle_new_we_rise_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  new_name text;
  configured_trial_days integer := 3;
  new_province text;
  new_city_town text;
  new_country text;
  incoming_referral text;
  referral_owner varchar(120);
  referral_program varchar(20);
begin
  select trial_days into configured_trial_days from public.payment_settings where id = 1;
  configured_trial_days := coalesce(configured_trial_days, 3);
  new_name := nullif(trim(coalesce(new.raw_user_meta_data ->> 'display_name', new.raw_user_meta_data ->> 'full_name', '')), '');
  if new_name is null then new_name := split_part(coalesce(new.email, 'We-Rise Lady'), '@', 1); end if;
  new_province := nullif(trim(coalesce(new.raw_user_meta_data ->> 'province', '')), '');
  new_city_town := nullif(trim(coalesce(new.raw_user_meta_data ->> 'city_town', '')), '');
  new_country := nullif(trim(coalesce(new.raw_user_meta_data ->> 'country', '')), '');
  incoming_referral := regexp_replace(upper(trim(coalesce(new.raw_user_meta_data ->> 'referral_code', ''))), '[^A-Z0-9]', '', 'g');

  if incoming_referral <> '' then
    select rp.member_key, rp.program_type
      into referral_owner, referral_program
    from public.referral_programs rp
    where upper(rp.referral_code) = incoming_referral
      and rp.status = 'active'
      and rp.member_key <> new.id::text
    limit 1;
  end if;

  insert into public.member_profiles (
    member_key, auth_user_id, email, display_name, province, city_town, country, plan, role, membership_status,
    trial_started_at, trial_ends_at, referred_by_member_key, referral_code_used, referral_program_used, referred_at,
    created_at, updated_at, last_seen_at
  ) values (
    new.id::text,
    new.id,
    lower(new.email),
    left(new_name, 80),
    left(new_province, 80),
    left(new_city_town, 100),
    left(new_country, 80),
    'free',
    'member',
    'trialing',
    now(),
    now() + make_interval(days => configured_trial_days),
    referral_owner,
    case when referral_owner is not null then incoming_referral else null end,
    referral_program,
    case when referral_owner is not null then now() else null end,
    now(),
    now(),
    now()
  )
  on conflict (member_key) do update
    set auth_user_id = excluded.auth_user_id,
        email = excluded.email,
        province = coalesce(public.member_profiles.province, excluded.province),
        city_town = coalesce(public.member_profiles.city_town, excluded.city_town),
        country = coalesce(public.member_profiles.country, excluded.country),
        referred_by_member_key = coalesce(public.member_profiles.referred_by_member_key, excluded.referred_by_member_key),
        referral_code_used = coalesce(public.member_profiles.referral_code_used, excluded.referral_code_used),
        referral_program_used = coalesce(public.member_profiles.referral_program_used, excluded.referral_program_used),
        referred_at = coalesce(public.member_profiles.referred_at, excluded.referred_at),
        updated_at = now();
  return new;
end;
$$;

alter table public.referral_programs enable row level security;
alter table public.referral_program_settings enable row level security;
alter table public.referral_link_clicks enable row level security;
alter table public.referral_conversions enable row level security;

-- Browser access remains through the Render API only; service_role bypasses RLS.
